name: media_tracker
description: A personal media tracking application for movies, TV shows, and anime.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  sqflite: ^2.4.0
  path: ^1.8.2
  provider: ^6.0.5
  csv: ^6.0.0
  cached_network_image: ^3.4.1
  file_picker: ^8.1.3 # Or the latest version
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
